###
# Migrate data from an old geonode version to the latest one (2.4).
#
---

- name: "clear old layers"
  sudo: yes
  sudo_user: postgres
  command: psql {{app_name}} -c "DELETE FROM layers_layer"

- name: "clear old resourcebase"
  sudo: yes
  sudo_user: postgres
  command: psql {{app_name}} -c "DELETE FROM base_resourcebase"

- name: "create view for bbox in legacy database"
  sudo: yes
  sudo_user: postgres
  shell: PGPASSWORD={{db_password}} psql -U {{db_user}} -h {{metadata_db}} {{db_metadata_instance}} -c "CREATE OR REPLACE VIEW maps_layer_bbox AS SELECT id, cast(bbox[1] as float) as bbox_x0, cast(bbox[2] as float) as bbox_y0, cast(bbox[3] as float) as bbox_x1, cast(bbox[4] as float) as bbox_y1 from (select id, string_to_array(replace(replace(replace(llbbox, ']',''), '[',''), ',',''), ' ') as bbox from maps_layer) as seq"

- name: "create new layers table view with bbox in legacy database"
  sudo: yes
  sudo_user: postgres
  shell: PGPASSWORD={{db_password}} psql -U {{db_user}} -h {{metadata_db}} {{db_metadata_instance}} -c "CREATE OR REPLACE VIEW augmented_maps_layer AS SELECT * FROM maps_layer INNER JOIN maps_layer_bbox USING (id) WHERE maps_layer_bbox.bbox_x0 > -181 and maps_layer_bbox.bbox_x1 < 181 and maps_layer_bbox.bbox_y0 > -91 and maps_layer_bbox.bbox_y1 < 90"


- name: "copy items to resourcebase"
  sudo: yes
  sudo_user: postgres
  shell: PGPASSWORD={{db_password}} psql -U {{db_user}} -h {{metadata_db}} {{db_metadata_instance}} -c "copy (select id, uuid, title, date, date_type, abstract, language, supplemental_information, 'EPSG:4326', 'csw_typename', 'csw_schema', 'csw_mdsource', 'csw_type', 'csw_wkt_geometry', false, 0, 0, false, true, bbox_x0, bbox_y0, bbox_x1, bbox_y1 from augmented_maps_layer) to stdout with csv" | psql {{app_name}} -c "copy base_resourcebase (id, uuid, title, date, date_type, abstract, language, supplemental_information, srid, csw_typename, csw_schema, csw_mdsource, csw_type, csw_wkt_geometry, metadata_uploaded, popular_count, share_count, featured, is_published, bbox_x0, bbox_y0, bbox_x1, bbox_y1) from stdin csv"


- name: "copy items to layer table"
  sudo: yes
  sudo_user: postgres
  shell: PGPASSWORD={{db_password}} psql -U {{db_user}} -h {{metadata_db}} {{db_metadata_instance}} -c 'copy (select id, title, abstract, purpose, constraints_other, supplemental_information, distribution_description, data_quality_statement, workspace, store, "storeType", name, typename, name from augmented_maps_layer) to stdout with csv' | psql {{app_name}} -c 'copy layers_layer (resourcebase_ptr_id, title_en, abstract_en, purpose_en, constraints_other_en, supplemental_information_en, distribution_description_en, data_quality_statement_en, workspace, store, "storeType", name, typename, charset) from stdin csv'


