- hosts: localhost
  connection: local

  tasks:
    - name: Delete postgres data instance, but create a snapshot before doing so
      rds:
        command: delete
        instance_name: "{{ db_data_instance }}"
        region: "{{ db_region }}"
        snapshot: postgres-data-snapshot-3
    - name: Delete postgres metadata instance, but create a snapshot before doing so
      rds:
        command: delete
        instance_name: "{{ db_metadata_instance }}"
        region: "{{ db_region }}"
        snapshot: postgres-metadata-snapshot-3
    - name: Delete postgres geonetwork instance, but create a snapshot before doing so
      rds:
        command: delete
        instance_name: "geonetwork"
        region: "{{ db_region }}"
        snapshot: postgres-geonetwork-snapshot-3
