- hosts: localhost
  pre_tasks:
  - name: ensure web server packages are installed
    apt: name={{item}}
    become: yes
    with_items:
      - curl
      - unzip
  vars:
    app_name: spade
    github_user: ewsterrenburg
    deploy_user: ubuntu
    code_repository: https://github.com/ADB-SPADE/SPADE.git
    server_name: adb-spade.org
    gs_users_xml: /data/geoserver/data/security/usergroup/default/users.xml
  roles:
   - { role: ansible-geonode }

