###
# Pulls the code from a remote Git repository, configures the web application,
# creates a virtualenv, and collects static assets
#
---
- name: ensure apt cache is up to date
  become: yes
  become_user: root
  apt: update_cache=yes

- name: install basic libraries
  become: yes
  become_user: root
  apt: name="{{ item }}" state=latest
  with_items:
    - vim
    - curl # should be installed in pre_tasks
    - make
    - git
    - unzip # should be installed in pre_tasks
    - zip

- name: install core python libraries
  become: yes
  become_user: root
  apt: name="{{ item }}" state=latest
  with_items:
    - python-software-properties
    - build-essential
    - python-dev
    - python-pip
    - python-apt

- name: install python virtual environment libraries
  become: yes
  become_user: root
  pip: name="{{ item }}" state=latest
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: install other required libraries
  become: yes
  become_user: root
  apt: name={{item}}
  with_items:
    - libpq-dev
    - postgresql-client-common
    - postgresql-client
    - python-imaging
    - python-lxml
    - python-pyproj
    - python-shapely
    - python-gdal
    - python-nose
    - python-httplib2
    - python-psycopg2
    - gettext
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
    - gdal-bin
    - libgeos-dev
    - libproj-dev
    - libjpeg-dev
    - libpng-dev

- name: install known_hosts file to access GitHub
  copy: src=known_hosts dest={{ssh_dir}}/known_hosts

- name: check if project template already exists
  stat:
    path: "{{app_code_dir}}/{{app_name}}"
  register: app_dir

- name: checkout latest web app code
  git: repo={{code_repository}} version={{branch_name}} dest={{app_code_dir}}/{{app_name}}
  when: github_user != "GeoNode" and (app_dir.stat.isdir is not defined)

- name: check if virtualenv already exists
  stat:
    path: "{{virtualenv_dir}}/{{app_name}}"
  register: venv_dir

- name: create virtualenv for Django web application
  shell: virtualenv --system-site-packages {{virtualenv_dir}}/{{app_name}}
  when: venv_dir.stat.isdir is not defined

- name: add virtualenvwrapper environment variables
  lineinfile:
    dest: "~/.bash_aliases"
    line: "{{ item }}"
    create: "yes"
  with_items:
    - "export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python"
    - "export WORKON_HOME=~/.venvs"
    - "source /usr/local/bin/virtualenvwrapper.sh"
    - "export PIP_DOWNLOAD_CACHE=$HOME/.pip-downloads"

- name: update pip in virtualenv to latest version
  pip: name=pip
       virtualenv={{virtualenv_dir}}/{{app_name}}
       extra_args='-U'

- name: install django to initialize the geonode-project template
  pip: name=Django
       version=1.8.7
       virtualenv={{virtualenv_dir}}/{{app_name}}
  when: github_user == "GeoNode"

- name: install bcrypt
  pip:
    name: "django[bcrypt]"
    virtualenv: "{{virtualenv_dir}}/{{app_name}}"

- name: checkout latest web app code from geonode-project template
  shell: cd {{app_code_dir}} && {{virtualenv_dir}}/{{app_name}}/bin/django-admin.py startproject {{app_name}} --template=https://github.com/GeoNode/geonode-project/archive/master.zip -epy,rst,yml -n Vagrantfile
  when: github_user == "GeoNode" and (app_dir.stat.isdir is not defined)

- name: copy the local_settings.py file in place
  template: src=local_settings.py.j2 dest={{app_code_dir}}/{{app_name}}/{{app_name}}/local_settings.py

# Just in local_settings now
#- name: patch the settings.py file in place
#  shell: sed -i -e "s/ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', \['localhost', \])/ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', \['localhost', '{{ server_name }}'\])/g" {{app_code_dir}}/{{app_name}}/{{app_name}}/settings.py
#  when: github_user != "GeoNode"

- name: check if requirements file exists
  stat:
    path: "{{app_code_dir}}/{{app_name}}/requirements.txt"
  register: requirements_file

- name: install web application dependencies listed in requirements.txt
  pip: requirements={{app_code_dir}}/{{app_name}}/requirements.txt virtualenv={{virtualenv_dir}}/{{app_name}}
  when: requirements_file.stat.exists

- name: install web application
  pip: name=file:///{{app_code_dir}}/{{app_name}}
       virtualenv={{virtualenv_dir}}/{{app_name}}
       extra_args='-e'

- name: create static directory for Django app if it does not exist
  file: path=/var/www/{{app_name}}/static state=directory mode=0777 owner=www-data group=www-data
  become: yes

- name: create uploaded directory for Django app if it does not exist
  file: path=/var/www/{{app_name}}/uploaded state=directory mode=0777 owner=www-data group=www-data
  become: yes

- name: create uploaded/layers directory for Django app if it does not exist
  file: path=/var/www/{{app_name}}/uploaded/layers/ state=directory mode=0777 owner=www-data group=www-data
  become: yes

- name: create uploaded/thumbs directory for Django app if it does not exist
  file: path=/var/www/{{app_name}}/uploaded/thumbs/ state=directory mode=0777 owner=www-data group=www-data
  become: yes

- name: create uploaded/avatars directory for Django app if it does not exist
  file: path=/var/www/{{app_name}}/uploaded/avatars/ state=directory mode=0777 owner=www-data group=www-data
  become: yes

- name: create uploaded/documents directory for Django app if it does not exist
  file: path=/var/www/{{app_name}}/uploaded/documents/ state=directory mode=0777 owner=www-data group=www-data
  become: yes

- name: rename the vassals-default.ini file to the app name
  file: src=/etc/uwsgi-emperor/vassals/vassals-default.skel dest=/etc/uwsgi-emperor/vassals/{{app_name}}.ini owner=www-data group=www-data state=link
  become: yes
  when: not apache

- name: create uwsgi log directory
  file: path=/var/log/uwsgi state=directory mode=0777 owner=www-data group=www-data
  become: yes
  when: not apache

- name: create nginx log directory
  file: path=/var/log/nginx state=directory mode=0777 owner=www-data group=www-data
  become: yes
  when: not apache

- name: make wsgi.py executable
  become: yes
  file:
    path: "{{app_code_dir}}/{{app_name}}/{{app_name}}/wsgi.py"
    mode: 0755
  when: apache

- name: create {{db_metadata_instance}} db
  postgresql_db: name={{db_metadata_instance}}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 owner={{db_user}}
                 template='template0'
  become: yes
  become_user: postgres

- name: add postgis to the {{db_metadata_instance}} db
  postgresql_ext: name=postgis db={{db_metadata_instance}}
  become: yes
  become_user: postgres

- name: create {{db_data_instance}} db
  postgresql_db: name={{db_data_instance}}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 owner={{db_user}}
                 template='template0'
  become: yes
  become_user: postgres

- name: add postgis to the {{db_data_instance}} db
  postgresql_ext: name=postgis db={{db_data_instance}}
  become: yes
  become_user: postgres

- name: make manage.py executable
  become: yes
  file:
    path: "{{app_code_dir}}/{{app_name}}/manage.py"
    mode: 0755

- name: Django makemigrations
  django_manage: command=makemigrations
                 app_path={{app_code_dir}}/{{app_name}}
                 virtualenv={{virtualenv_dir}}/{{app_name}}
                 settings={{main_module}}.settings

- name: Django migrate specific modules
  when: github_user == "GeoNode"
  ignore_errors: yes
  django_manage: command="migrate {{item}}"
                 app_path={{app_code_dir}}/{{app_name}}
                 virtualenv={{virtualenv_dir}}/{{app_name}}
                 settings={{main_module}}.settings
  with_items:
    - auth
    - account
    - people
    - sites
    - layers
    - documents
    - admin

- name: Django migrate
  django_manage: command=migrate
                 app_path={{app_code_dir}}/{{app_name}}
                 virtualenv={{virtualenv_dir}}/{{app_name}}
                 settings={{main_module}}.settings

- name: Django syncdb
  django_manage: command=syncdb
                 app_path={{app_code_dir}}/{{app_name}}
                 virtualenv={{virtualenv_dir}}/{{app_name}}
                 settings={{main_module}}.settings

- name: Django collectstatic
  django_manage: command=collectstatic
                 app_path={{app_code_dir}}/{{app_name}}
                 virtualenv={{virtualenv_dir}}/{{app_name}}
                 settings={{main_module}}.settings

- name: wait for geoserver to be up
  shell: curl --head --silent http://localhost:{{ gs_port }}/geoserver/web/
  register: result
  until: result.stdout.find('200 OK') != -1
  retries: 5
  delay: 60

- name: Copy create_db_store script in place
  template: src=create_db_store.py.j2 dest={{app_code_dir}}/{{app_name}}/create_db_store.py

- name: create the db datastore in geoserver
  command: "{{virtualenv_dir}}/{{app_name}}/bin/python {{app_code_dir}}/{{app_name}}/create_db_store.py"

- name: template superusers fixture in place
  template:
    src: superusers.json.j2
    dest: "~/superusers.json"

- name: load superusers fixture
  django_manage: command="loaddata ~/superusers.json"
                 app_path={{app_code_dir}}/{{app_name}}
                 virtualenv={{virtualenv_dir}}/{{app_name}}
                 settings={{main_module}}.settings

- name: check if oauth configuration exists
  stat:
    path: /var/lib/tomcat8/webapps/geoserver/data/security/filter/geonode-oauth2/config.xml
  register: geonode_oauth_config

- name: Copy oauth fixture in place
  template: src=default_oauth_apps.json.j2 dest={{app_code_dir}}/{{app_name}}/default_oauth_apps.json
  when: geonode_oauth_config.stat.exists

- name: Load oAuth fixture
  when: geonode_oauth_config.stat.exists
  django_manage: command="loaddata {{app_code_dir}}/{{app_name}}/default_oauth_apps.json"
                 app_path={{app_code_dir}}/{{app_name}}
                 virtualenv={{virtualenv_dir}}/{{app_name}}
                 settings={{main_module}}.settings
