###
# Install GeoServer from Custom GeoNode Build 
#
---

- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: install Tomcat 
  apt: pkg={{ item }} state=present
  sudo: yes
  with_items:
   - tomcat8

- name: Download GeoServer (remote)
  sudo: yes
  get_url:
    dest=/var/lib/tomcat8/webapps/geoserver.war
    url={{ geoserver_url }}
    owner=0
    group=0
    mode=0644

- name: Wait for GeoServer to be unpacked
  wait_for:
    path: /var/lib/tomcat8/webapps/geoserver/data/geogig/config/security/logstore.properties

- name: Adding SQLite logstore setting
  sudo: yes
  lineinfile:
    dest: "/var/lib/tomcat8/webapps/geoserver/data/geogig/config/security/logstore.properties"
    regexp: "^url="
    line: "url=jdbc:sqlite://var/lib/tomcat8/webapps/geoserver/data/geogig/config/security/securitylogs.db"
    state: "present"

- name: Restarting Tomcat
  sudo: yes
  service:
    name: tomcat8
    state: restarted
