###
# Pulls the code from Pypi
#
---
- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: ensure needed packages are installed
  apt: name={{item}}
  sudo: yes
  with_items:
    - rabbitmq-server
    - python-numpy

- name: check if virtualenv already exists
  stat:
    path: "{{virtualenv_dir}}/{{app_name}}"
  register: venv_dir

- name: create virtualenv if does not exist already
  shell: virtualenv --system-site-packages {{virtualenv_dir}}/{{app_name}}
  when: venv_dir.stat.isdir is not defined

- name: update pip in virtualenv to latest version
  pip: name=pip
       virtualenv={{virtualenv_dir}}/{{app_name}}
       extra_args='-U'

- name: install django-osgeo-importer
  pip: name=django-osgeo-importer
       version=0.1.1a1
       virtualenv={{virtualenv_dir}}/{{app_name}}


