###
# Install PostGIS and Postgres 9.5 from the UbuntuGIS repo.
#
---
# - name: configure the PostgreSQL APT key
#   apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
#   become: yes

# - name: configure the PostgreSQL APT repositories
#   apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" state=present
#   become: yes

- name: configure the UbuntuGIS ppa repository
  become: yes
  apt_repository:
    repo: 'ppa:ubuntugis/ubuntugis-unstable'

- name: install PostGIS
  become: yes
  apt: pkg={{ item }} state=present
  with_items:
   - python-psycopg2
   - postgresql-9.5
   - postgresql-contrib-9.5
   - postgresql-9.5-postgis-2.3


- name: check if postgres cluster is created already
  become: yes
  become_user: postgres
  shell: "psql postgres -c 'select 1'"
  register: db_setup
  ignore_errors: yes

- name: setup postgres cluster to default to utf8
  # if the dbs haven't been created yet, we want to destroy the whole db
  # cluster and recreate it with proper utf8 support. From http://ph.ly/pg
  become: yes
  shell: "pg_createcluster --start -e UTF-8 9.5 main"
  when: db_setup.rc != 0 # only do this if the dbs haven't been created yet

- name: create database user
  become: yes
  become_user: postgres
  postgresql_user: name={{db_user}}
                   password={{db_password}}
                   role_attr_flags=LOGIN,CREATEDB,NOSUPERUSER

- name: "copy {{ pg_hba_conf }} file"
  become: yes
  become_user: postgres
  copy:
    src: pg_hba.conf
    dest: "{{ pg_hba_conf }}"

- name: "patch {{ postgresql_conf }}"
  become: yes
  become_user: postgres
  lineinfile:
    dest: "{{ postgresql_conf }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^#?max_connections\\s*="
      line: "max_connections = {{ pg_max_connections }}"
    - regexp: "^#?shared_buffers\\s*="
      line: "shared_buffers = {{ pg_shared_buffers }}"

- name: restart postgres
  become: yes
  become_user: root
  command: /etc/init.d/postgresql restart
