###
# updates the APT package cache and install packages necessary for web
# servers
#
---

- name: ensure apt cache is up to date
  apt: update_cache=yes 
  sudo: yes

- name: ensure web server packages are installed
  apt: name={{item}}
  sudo: yes
  with_items:
    - git
    - python-dev
    - libpq-dev
    - python-virtualenv
    - nginx
    - supervisor
    - postgresql-client-common
    - postgresql-client
    - python-dev
    - python-imaging
    - python-lxml
    - python-pyproj
    - python-shapely
    - python-gdal
    - python-nose
    - python-httplib2
    - python-software-properties
    - gettext
    - build-essential
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
    - gdal-bin
    - libgeos-dev
    - libproj-dev
    - unzip
    - zip
    - libjpeg-dev
    - libpng-dev
    - libxslt-dev
